### ISSUE TITLE
uncommented debug code

### ISSUE THREAD

**Issue by SerinaNya** [super-coffee/bugjang-status#2]
https://github.com/super-coffee/bugjang-status/blob/3d5d269a4a555a9f05c041b301fd6dbf6171dfe1/index.js#L27

this should be commented with `//`

> because i use the phone, it is not convient to change it

**Comment by SerinaNya** [comment]
besides, please add a link at the copyright @mcoo 
``` html
<a target="_blank" href="https://github.com/super-coffee/bugjang-status" title="GitHub">Bugjang-Status</a>
```

**Comment by mcoo** [comment]
ok

**Comment by SerinaNya** [comment]
where is the link?

**Comment by mcoo** [comment]
ok  = =
